# Generated by Django 3.0 on 2020-03-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Médico', 'verbose_name_plural': 'Médicos'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'Especialidade', 'verbose_name_plural': 'Especialidades'},
        ),
    ]
