# Generated by Django 3.0 on 2020-03-21 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
            ],
            options={
                'db_table': 'appointment_times',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('horarios', models.ManyToManyField(related_name='appointment_time', to='schedule.AppointmentTime')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_name', to='doctor.Doctor')),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
    ]
