# Generated by Django 3.0 on 2020-03-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmenttime',
            options={'verbose_name': 'Horário', 'verbose_name_plural': 'Horários'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Agenda', 'verbose_name_plural': 'Agendas'},
        ),
    ]
